### ISSUE TITLE
idea: runtime linking

### ISSUE THREAD

**Issue by undroidwish** [mattadams/Rtcl#1]
In order to not hard code dependencies into the Tcl extension I did some
experimentation, see https://www.androwish.org/home/dir?name=undroid/Rtcl

Should you find pieces of it useful, I'll be happy if you take 'em over.

All the best,
Christian

**Comment by mattadams** [comment]
Thank you, Christian. Believe it or not I have finally gotten around to merging most of your changes into Rtcl.

I came across a bug in `generic/rtcl.c` that had been introduced into `REval`. You may wish to patch this fix back into your source tree otherwise Rtcl will fail to evaluate any further than the first expression passed to it. The change is:

```
@@ -468,7 +488,7 @@                                                                                                    
   *s = R_NilValue;                                                                                                    
                                                                                                                       
   for (i = 0; i < l; i++) {                                                                                           
-    val = R_tryEval(VECTOR_ELT(exp, 0), R_GlobalEnv, &evalError);                                                     
+    val = R_tryEval(VECTOR_ELT(exp, i), R_GlobalEnv, &evalError);                                                     
                                                                                                                       
     if (evalError) {                                                                                                  
       Rf_unprotect(2);         
```

Cheers,
Matt
